services:
  user-frontend:
    build: ./user-frontend
    depends_on:
      - backend
    environment:
      BACKEND_URL: http://backend:8080
    restart: unless-stopped

  admin-frontend:
    build: ./admin-frontend
    restart: unless-stopped

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: clinic
      DB_PASSWORD: clinicpass
      DB_NAME: clinicdb
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: clinicdb
    environment:
      POSTGRES_USER: clinic
      POSTGRES_PASSWORD: clinicpass
      POSTGRES_DB: clinicdb
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      
    depends_on:
      - user-frontend
      - admin-frontend
      - backend
    restart: unless-stopped

volumes:
  db-data:
